services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "8028:8028"
    depends_on:
      - server_1
      - server_2
    networks:
      static-network:
        ipv4_address: 172.22.1.2

  server_1:
    build: ./deploy1/
    networks:
      static-network:
        ipv4_address: 172.22.1.3
  server_2:
    build: ./deploy2/
    networks:
      static-network:
        ipv4_address: 172.22.1.4

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.1.0/16
