services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABSE: scribble_sync
    ports:
      - '3306:3306'
    volumes:
      - datadir:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  datadir:

